name: Generate Snake and Activity Graph

on:
  schedule:
    - cron: "0 0 * * *" # roda todo dia à meia-noite
  workflow_dispatch:

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: JKSJ15
          outputs: dist/snake.svg

      - name: Commit and push snake
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add dist/snake.svg
          git commit -m "Atualizando cobrinha"
          git push

  activity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Activity Graph
        uses: Ashutosh00710/github-readme-activity-graph@master
        with:
          username: JKSJ15
          theme: github
          output: dist/activity-graph.svg

      - name: Commit and push graph
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add dist/activity-graph.svg
          git commit -m "Atualizando gráfico de atividades"
          git push
